plugins {
    id 'java'
    id 'com.gradleup.shadow' version '9.4.2'
    id 'com.azuredoom.hytale-tools' version '1.0.48'
    id 'com.azuredoom.hytalepublisher' version '1.+'
}

group = "com.riprod"
version = project.version

repositories {
    mavenCentral()
    gradlePluginPortal()
    maven { url = uri("https://www.cursemaven.com") }
}

configurations {
    shadowBundle
    implementation.extendsFrom(shadowBundle)
}

dependencies {
    shadowBundle 'com.riprod:configly:1.+'
}

shadowJar {
    archiveClassifier.set('')
    configurations = [project.configurations.shadowBundle]
}

hytaleTools {
    javaVersion = project.java_version as Integer
    hytaleVersion = project.hytale_version.toString()
    manifestServerVersion = project.manifestServerVersion.toString()
    manifestGroup = project.manifest_group.toString()
    modId = project.mod_id.toString()
    modDescription = project.mod_description.toString()
    modUrl = project.mod_url.toString()
    mainClass = project.main_class.toString()
    modCredits = project.mod_credits.toString()
    manifestDependencies = project.manifest_dependencies.toString()
    manifestOptionalDependencies = project.manifest_opt_dependencies.toString()
    curseforgeId = project.curseforgeID.toString()
    disabledByDefault = project.disabled_by_default.toString().toBoolean()
    includesPack = project.includes_pack.toString().toBoolean()
    patchline = project.patchline.toString()

    debugEnabled = true
    debugSuspend = false

    requireDcevm = true
}

hytalePublisher {
    version       = project.version
    changelogFile = "changelog.md"
    gameVersion   = project.hytale_version.toString()

    modtale {
        enabled   = true
        projectId = project.modtale_uuid
        patchline = project.patchline.toString()
    }

    curseforge {
        enabled   = true
        projectId = project.curseforgeID

        embeddedLibrary "configly"
    }

    modifold {
        enabled   = true
        projectId = project.modifold_id

        embedded "configly"
    }

        github {
        enabled = true

        generateReleaseNotes = true
        includeJar        = true
        includeSourcesJar = true
        includeJavadocJar = true    
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of((project.java_version as String).toInteger())
    }
    withSourcesJar()
    withJavadocJar()
}
