org.gradle.jvmargs=-Xmx1G
org.gradle.caching=false
org.gradle.configuration-cache=false
org.gradle.java.home                 = /usr/lib/jvm/java-25-openjdk

# Common
java_version                         = 25
hytale_version                       = 0.+
manifestServerVersion                = >=0.5.0 <0.7.0

# Publishing
modtale_uuid                         = 
modifold_id                          = 
curseforgeID                         = 

# Mod options
group                                = com.riprod.veinminly
manifest_group                       = Riprod
mod_name                             = Veinminly
main_class                           = com.riprod.veinminly.VeinminlyPlugin
mod_author                           = Riprod
mod_id                               = Veinminly
mod_license                          = MIT
mod_description                      = Instantly mine connected ores and blocks by holding the Walk key (LEFT ALT). /veinmining to configure.
mod_credits                          = Riprod, EineNT
mod_logo                             = icon-256.png
mod_url                              = https://modtale.net/mod/veinminly
mod_issues                           = https://github.com/itsriprod/veinminly/issues
mod_sources                          = https://github.com/itsriprod/veinminly
version                              = 2.3.0
includes_pack                        = true
disabled_by_default                  = false
patchline                            = release
load_user_mods                       = false
manifest_dependencies                = 
manifest_opt_dependencies            = 